# Generated by Django 5.0.1 on 2025-04-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_name", models.CharField(max_length=100, unique=True)),
                ("video_url", models.URLField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("flocking_index", models.CharField(max_length=50)),
                ("avg_tel", models.CharField(max_length=50)),
                ("avg_ta", models.CharField(max_length=50)),
                ("avg_group_speed", models.CharField(max_length=50)),
            ],
        ),
    ]
