# Generated by Django 5.0.1 on 2025-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="analyzed_video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
